# Generated by Django 3.2.5 on 2021-07-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
