# Generated by Django 3.2.5 on 2021-07-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
